version: 2
workspace-name: &working_directory /tmp/workspace
machine:
  timezone: Europe/Berlin
jobs:
  build:
    docker:
      - image: gradle:5.5-jdk11
    working_directory: *working_directory
    steps:
      - checkout
      - attach_workspace:
          at: *working_directory
      - restore_cache:
          keys:
            - gradle-dependencies-{{ checksum "build.gradle" }}
            - gradle-dependencies-
      - run:
          name: Build, test, generate dependency report
          command: gradle clean dependencyUpdates build --project-cache-dir=~/.gradle --stacktrace --no-daemon --build-cache
          environment:
            GRADLE_OPTS: -Xmx2048m -Dfile.encoding=UTF-8 -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true
            GRADLE_HOME: ~/.gradle
      - run:
          name: Upload code coverage
          command: bash <(curl -s https://codecov.io/bash)
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-dependencies-{{ checksum "build.gradle" }}
      - persist_to_workspace:
          root: ./
          paths:
            - build/libs/kotlin-starter.jar
            - Dockerfile
            - build/reports
      - store_artifacts:
          path: build/libs/kotlin-starter.jar
      - store_artifacts:
          path: build/reports/dependencies/report.txt
      - store_test_results:
          path: build/test-results/test
  push-docker-image:
    docker:
      - image: alpine:latest
    working_directory: *working_directory
    steps:
      - run:
          name: Install dependencies
          command: apk -U add --no-cache docker ca-certificates
      - attach_workspace:
          at: *working_directory
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t kotlin-starter .
  deploy: &deploy
    docker:
      - image: alpine:latest
    working_directory: *working_directory
    steps:
      - run:
          name: Install dependencies
          command: apk -U add --no-cache ca-certificates
      - attach_workspace:
          at: *working_directory
      - run:
          name: Deploy to environment
          command: echo "deploying to $ENVIRONMENT"
  deploy-to-staging:
    environment:
      ENVIRONMENT: staging
    <<: *deploy
  deploy-to-production:
    environment:
      ENVIRONMENT: production
    <<: *deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context: analysis
      - push-docker-image:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-to-staging:
          requires:
            - push-docker-image
          filters:
            branches:
              only: master
      - hold:
          type: approval
          requires:
            - deploy-to-staging
          filters:
            branches:
              only: master
      - deploy-to-production:
          requires:
            - hold
          filters:
            branches:
              only: master
